# Generated by Django 3.2.13 on 2022-10-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('jangsa', '장사소식'), ('singsing', '싱싱상회'), ('knowhow', '배민노하우')], default='jangsa', max_length=10),
        ),
    ]
